version: '3.9'
name: 'bachelor_semifinal'

services:
  scene:
    image: registry.gitlab.com/beerlab/iprofi2024/problem/bachelor/scene:latest
    container_name: scene_bachelor_semifinal
    environment:
      - DISPLAY
      - XAUTORITY
      - RVIZ_GUI=true
      - GAZEBO_GUI=true
    ipc: host
    stdin_open: true
    tty: true
    networks:
      - general
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev

  solution:
    image: registry.gitlab.com/beerlab/iprofi2024/problem/bachelor/base:latest
    container_name: solution_bachelor_semifinal
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://scene:11311
      - DISPLAY
      - XAUTORITY
      - GUI=true
    depends_on: 
      scene:
        condition: service_healthy
    networks:
      - general
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./:/ros_ws/src/solution_bachelor


networks:
  general:
    attachable: true
    internal: false
    driver: bridge